# Template trainer

# training settings
batch_size: 4
max_epochs: 500
optim_name: adamw
optim_lr: 0.0003
reg_weight: 0.01
val_every: 50
lrschedule: warmup_cosine
warmup_epochs: 10
seed: 42
iter_per_epoch: 250
train_by_iter: True
deep_supervision: False
save_checkpoint: True
