dataset_name: synapse
data_dir: data/synapse_data_clean

crop_nums: 4
in_channels: 1
out_channels: 9
space_x: 1.5
space_y: 1.5
space_z: 2.0
roi_x: 128 # prev 96
roi_y: 128 # prev 96
roi_z: 128 # prev 96
